### ISSUE TITLE
Implement at least one default color scheme for site

### ISSUE THREAD

**Issue by Ethan-Harris07** [Pv3-Labs/gibberle#26]
## Description
Come up with at least one color scheme for the site. This includes background, primary/secondary colors, text color, color for what we want most of the buttons to look like, icon colors

## Acceptance Criteria
Have 3 color schemes on the color scheme page of the figma doc
Name the colors so they can be used in the website

## Dev Notes
Use [Real time colors](https://www.realtimecolors.com/?colors=050315-fbfbfe-2f27ce-dedcff-433bff&fonts=Inter-Inter) if you want to visualize what different color schemes will look like on a generic website layout
[figma](https://www.figma.com/design/3FNhMXGGHrPWNaWNxGhjUE/Gibberle-Figma-(CLICK-THIS-ONE-TO-IMPLEMENT-DESIGNS)?node-id=2241-528&node-type=canvas&t=thCqrMJ8ttnr7VdT-0)

**Comment by CalvinDudd** [comment]
@Ethan-Harris07 I'm a big fan of the dark theme vibe, one color scheme that could be unique & vibrant is Dark Gray and solarized orange. If you had 3 colors in mind, Dark gray, solarized orange & purple. (Not sure what shade of purple)

Just a thought.
