### ISSUE TITLE
User Data Database Schema

### ISSUE THREAD

**Issue by CalvinDudd** [Pv3-Labs/gibberle#44]
## Description
Rough draft schema for our user stats object to be used in Firestore.

## Acceptance Criteria
Research and document the following:
- Create a rough draft database schema meant to represent user stats.
## Dev Notes
[Research doc link](https://docs.google.com/document/d/1GUzfNI29ZAa_qYrLUwzFuJeGDsM_YeVBdxYKD9pyuBQ/edit?usp=sharing)

**Comment by CalvinDudd** [comment]
@marcus-gustafson Take a look at this when you get the chance.

**Comment by marcus-gustafson** [comment]
Looks pretty good. Left a few comments on the doc.
