### ISSUE TITLE
MVP Presentation

### ISSUE THREAD

**Issue by Exiledz5155** [Pv3-Labs/gibberle#77]
## Description
This is a ticket to track our progress on the MVP presentation.

## Acceptance Criteria
The presentation should roughly include:
- Introduction to concept of the game (maybe include some history)
- A section for features, ML, Demo, and future updates

## Dev Notes
[Link the presentation here](https://docs.google.com/presentation/d/15D-2TVR44TBrZa0by4Pp-8_jTWpwp90zTREZRRYga1k/edit?usp=sharing)

## Subtasks
- [ ] Subtask 1
- [ ] Subtask 2

**Comment by CalvinDudd** [comment]
Added some details on our backend implementation  & philosophy.
