### ISSUE TITLE
Research system design and update design doc

### ISSUE THREAD

**Issue by Exiledz5155** [Pv3-Labs/gibberle#8]
## Description
We need to do more research on how to put all the pieces together for the project, from frontend to backend and cloud.

Lead: @Exiledz5155 

## Acceptance Criteria
- Design doc should have a presentable diagram for the project architecture 
- Create a separate doc to keep track of research, which will include alt technologies
- Create test projects for cloud 

## Dev Notes
[@Exiledz5155 will link doc ](https://docs.google.com/document/d/1j9WP7BQ0aP4KIlJ4xy6g6eHN1KLjN12pVcU2aKGkX_A/edit?usp=sharing)

## Subtasks
- [x] #12 
- [x] #16
- [x] #17
- [x] Assess backend from a high-level, and outline potential paths
- [ ] #19 
- [x] #18 
- [ ] #1

**Comment by Exiledz5155** [comment]
- [ ] #12

**Comment by CalvinDudd** [comment]
Added some of my thoughts in the backend research google doc.

Take a look here if you'd like: [Doc](https://docs.google.com/document/d/1j9WP7BQ0aP4KIlJ4xy6g6eHN1KLjN12pVcU2aKGkX_A/edit)
